version: '3'

services:
  api:
    build:
      context: .
      target: apiservice
    ports:
      - "8000:8000"
    networks:
      - fishnet_network
    volumes:
      - timeseries:/app/timeseries
    environment:
      - FISHNET_MESSAGE_CHANNEL=${FISHNET_MESSAGE_CHANNEL}
      - FISHNET_MESSAGES_KEY=${MESSAGES_KEY}
      - FASTAPI_WALLETAUTH_APP=${FASTAPI_WALLETAUTH_APP}
      - FASTAPI_WALLETAUTH_PRIVATE_KEY=${FASTAPI_WALLETAUTH_PRIVATE_KEY}
      - MESSAGE_CHANNEL=${MESSAGE_CHANNEL}
      - FISHNET_MESSAGE_CHANNEL=${FISHNET_MESSAGE_CHANNEL}
      - MESSAGES_KEY=${MESSAGES_KEY}
      - API_URL=http://api:8000

  local_listener:
    depends_on:
      - api
    build:
      context: .
      target: listenerservice
    ports:
      - "8001:8000"
    networks:
      - fishnet_network
    environment:
      - FISHNET_MESSAGE_CHANNEL=${FISHNET_MESSAGE_CHANNEL}
      - FISHNET_MESSAGES_KEY=${MESSAGES_KEY}
      - FASTAPI_WALLETAUTH_APP=${FASTAPI_WALLETAUTH_APP}
      - FASTAPI_WALLETAUTH_PRIVATE_KEY=${FASTAPI_WALLETAUTH_PRIVATE_KEY}
      - MESSAGE_CHANNEL=${MESSAGE_CHANNEL}
      - FISHNET_MESSAGE_CHANNEL=${FISHNET_MESSAGE_CHANNEL}
      - MESSAGES_KEY=${MESSAGES_KEY}
      - API_URL=http://api:8000

volumes:
  timeseries:

networks:
  fishnet_network:
    driver: bridge