version: '3'

services:
  api:
    build:
      context: ./src/fishnet_cod/api
    ports:
      - "8000:8000"
    networks:
      - fishnet_network
    environment:
      - FISHNET_MESSAGE_CHANNEL=FISHNET_DEMO_BERLIN_1
      - FISHNET_MESSAGES_KEY=<enter-your-private-key-here>

  local_listener:
    depends_on:
      - api
    build:
      context: ./src/fishnet_cod/local_listener
    ports:
      - "8001:8000"
    networks:
      - fishnet_network
    environment:
      - API_URL=http://api:8000
      - FISHNET_MESSAGE_CHANNEL=FISHNET_DEMO_BERLIN_1

  indexer:
    image: dipfit/fishnet-indexer:latest
    ports:
      - "8002:8080"
    networks:
      - fishnet_network
    environment:
      - SOLANA_RPC=<enter-your-RPC-url-here>
      - SPL_TOKEN_MINTS=kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6
      - NODE_OPTIONS=--max-old-space-size=4096
      - SOLANA_MAIN_PUBLIC_RPC=https://api.mainnet-beta.solana.com

  marketplace:
    image: dipfit/fishnet-marketplace:latest
    ports:
      - "8003:50825"
    networks:
      - fishnet_network
    environment:
      - MESSAGES_KEY=<enter-your-private-key-here>
      - INDEXER_API=http://indexer:8080
      - ALEPH_CHANNEL=FISHNET_DEMO_BERLIN_1
      - RPC=<enter-your-RPC-url-here>
      - PORT=50825


networks:
  fishnet_network:
    driver: bridge
