version: '3'

services:
  api:
    build:
      context: ./src/fishnet_cod/api
    ports:
      - "8000:8000"
    networks:
      - fishnet_network

  local_listener:
    depends_on:
      - api
    build:
      context: ./src/fishnet_cod/local_listener
    ports:
      - "8001:8000"
    networks:
      - fishnet_network
    environment:
      - API_URL=http://api:8000

  indexer:
    image: ricardocr987/indexer:latest
    ports:
      - "8002:8000"
    networks:
      - fishnet_network
    environment:
      - SOLANA_RPC=https://rpc.helius.xyz/?api-key=fc7522c9-052e-4788-a7dc-10780b0eb50a
      - SPL_TOKEN_MINTS=kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6
      - NODE_OPTIONS=--max-old-space-size=4096
      - SOLANA_MAIN_PUBLIC_RPC=https://api.mainnet-beta.solana.com

networks:
  fishnet_network:
    driver: bridge
